### ISSUE TITLE
Please make a Visual Studio 2019 project for it

### ISSUE THREAD

**Issue by Zero3K** [maxrigout/Remote#1]
*subject*

And if you do, also please have it use the libraries that are included with Windows by default (so a user doesn't have to install a redistribution package).

**Comment by Zero3K** [comment]
I discovered that using Multi-threaded results in a 360-370 KB/s when compiled as a Release build via Visual Studio 2019. You can read on how to set that by going to https://docs.microsoft.com/en-us/cpp/build/reference/md-mt-ld-use-run-time-library?view=vs-2019.

**Comment by maxrigout** [comment]
if you use visual studio, an empty c++ project is all that's needed to compile this (just 1 file). As far as the redistribution packages, you can include it all in the exe using this tutorial: 
https://www.codeproject.com/Tips/851725/Visual-Cplusplus-How-to-Create-Standalone-Win-Appl

**Comment by Zero3K** [comment]
I made a Pull Request to add a Visual Studio 2019 Project. Its at https://github.com/maxrigout/Remote/pull/15.
