### ISSUE TITLE
Issue with the text that shows the Tab Key being pressed/released

### ISSUE THREAD

**Issue by Zero3K** [maxrigout/Remote#12]
The text in the console that shows the Tab Key being pressed/released isn't aligned properly. When its pressed, the "TAB DOWN" text is being placed outside of the box.  When its released, only the "UP" of "TAB UP" is showing.

**Comment by maxrigout** [comment]
This is due to the function MapVirtualKeyA which returns the character '\t' which is a tabulation. I would need to manually map the virtual key to a char*, but in that case, why not do it for all the other keys ? I'll look into it maybe someday, but not now. I'll leave it open.

**Comment by Zero3K** [comment]
That makes sense to me.

**Comment by Zero3K** [comment]
Why did you close this?
