### ISSUE TITLE
Visual Studio 2019's Code Analysis found some issues with the code

### ISSUE THREAD

**Issue by Zero3K** [maxrigout/Remote#17]
Visual Studio 2019's Code Analysis found some issues with the code. Here's the log of what it found:

[Remote_Code_Analysis_VS2019.log](https://github.com/maxrigout/Remote/files/5434061/Remote_Code_Analysis_VS2019.log)

**Comment by maxrigout** [comment]
these aren't really issues. Just warnings the compiler gives. Some of these are irrelevant, other could be addressed. But it doesn't affect the functionality of the code.
