### ISSUE TITLE
Windows Release Binary

### ISSUE THREAD

**Issue by Zero3K** [maxrigout/Remote#20]
Please provide one (it should have a version of v1.01 or something).

**Comment by maxrigout** [comment]
I just wanted to upload the source code. You can compile it however you want, using whatever compiler you want.

**Comment by Zero3K** [comment]
You can set it up to compile builds automatically.

**Comment by maxrigout** [comment]
compiled and uploaded a binary. Should be standalone.

**Comment by Zero3K** [comment]
I can confirm that it is standalone.

**Comment by Zero3K** [comment]
I think the version number being used for the release should be at v1.05 or v1.1 since v1.0 should've been used when it had no changes done to it.
