### ISSUE TITLE
Support multiple clients

### ISSUE THREAD

**Issue by Zero3K** [maxrigout/Remote#24]
It would be nice if it could support multiple clients so in case Gamepad support gets added, multiple people can connect and each can be a player in whatever game the user wants to play with them.

**Comment by maxrigout** [comment]
this is completely unrelated to this project. My program enables one user to control another computer. By control I mean the user's computer (server) sends inputs to another computer (client). What you describe would be multiple clients sending their inputs to the server. While it might not be too hard to implement, it is beyond the scope of this project

**Comment by Zero3K** [comment]
So, someone else will have to implement it?

**Comment by maxrigout** [comment]
sure, why not ? While I do recognize the value in adding a feature like that, this is not the focus nor the purpose of this project.
If someone wanted to do something like that, they'd need to create some sort of "virtual controllers" using custom drivers and stuff. I'm not an expert, but this is what I'd expect from a project like that.
My project only spoofs the inputs from mouse and keyboard (potentially other hid devices) and transmits them to other computers.
So for now, yes, someone else will have to implement that.
