### ISSUE TITLE
Lag issues

### ISSUE THREAD

**Issue by maxrigout** [maxrigout/Remote#25]
the speed is measured in pixels/update. The program detects any change in the x and the y of the mouse and send those changes to the client. Therefore, theoretically, the speed should be consistent. I do have lag issues when I use it. I'm unsure of how to fix this right now.

_Originally posted by @maxrigout in https://github.com/maxrigout/Remote/issues/23#issuecomment-716092350_

**Comment by Zero3K** [comment]
Is it a bandwidth issue?

**Comment by maxrigout** [comment]
seems to work fine now

**Comment by MegaZeroX10** [comment]
Thanks for fixing it.
