### ISSUE TITLE
Make Release Builds automatically

### ISSUE THREAD

**Issue by Zero3K** [maxrigout/Remote#26]
It would be nice if that could be done so you don't have to make them manually.

**Comment by maxrigout** [comment]
I'm still new to github, I'll have to take a look into it. I'm not sure when this will be done

**Comment by Zero3K** [comment]
https://cmakeconverter.readthedocs.io/en/latest/intro.html
https://github.com/maxrigout/Remote/actions

**Comment by MegaZeroX10** [comment]
Why did you close this issue?
