### ISSUE TITLE
Name change

### ISSUE THREAD

**Issue by Zero3K** [maxrigout/Remote#5]
I think its name should be changed since Remote is too generic and it deserves a better name.

**Comment by maxrigout** [comment]
yes I agree, I used "remote" because I was not inspired at all so if you have any suggestions, I'll consider them. Thanks

**Comment by Zero3K** [comment]
Remoukey is all I can come up with at this time.

**Comment by maxrigout** [comment]
yeah, I'm not sure

**Comment by midaspt** [comment]
I propose something along the lines of **OpenRemote** or **OpenKVM**.

If a more characteristic moniker is desired, then what about **Synchronicity**?
